#!/bin/bash
#
# Copyright (C) 2000-2023 Kern Sibbald
# License: BSD 2-Clause; see file LICENSE-FOSS
#
# This is a base32 unit test
#
TestName="base32_test"
. scripts/functions
make -C $src/src/lib $TestName

$bin/$TestName
exit $?
