#!/usr/bin/env bash
#
# Copyright (C) 2000-2023 Kern Sibbald
# Copyright (C) 2021-2023Bacula Systems SA
# License: BSD 2-Clause; see file LICENSE-FOSS
#
# Run cppcheck
#

cppcheck --quiet --enable=all --std=c++11 --force --suppress=unreadVariable --suppress=cstyleCast --language=c++ ../bacula/src
