#!/bin/bash
#
# Copyright (C) 2000-2022 Kern Sibbald
# License: BSD 2-Clause; see file LICENSE-FOSS
#
#
# This is a Docker Plugin DKID unit test
#
. scripts/regress-utils.sh
do_regress_unittest "test_dkid" "src/plugins/fd/docker"
