#!/bin/bash
#
# Copyright (C) 2000-2015 Kern Sibbald
# License: BSD 2-Clause; see file LICENSE-FOSS
#
# This is an alist unit test
#

TestName="edit_test"
. scripts/functions
make -C $src/src/lib $TestName

$bin/$TestName
exit $?

