#!/bin/bash
#
# Copyright (C) 2000-2025 Kern Sibbald
# License: BSD 2-Clause; see file LICENSE-FOSS
#
# This is an ilist unit test
#
TestName="ilist_test"
. scripts/functions
make -C $src/src/lib $TestName

$bin/$TestName
exit $?
