#!/bin/bash
#
# Copyright (C) 2000-2019 Kern Sibbald
# License: BSD 2-Clause; see file LICENSE-FOSS
#
# This is an bsscanf unit test
#
TestName="scan_test"
. scripts/functions
make -C $src/src/lib $TestName

$bin/$TestName
exit $?
