#!/bin/bash
#
# Copyright (C) 2000-2018 Kern Sibbald
# License: BSD 2-Clause; see file LICENSE-FOSS
#
# This is a test for debug tags
#
TestName="tags_test"
. scripts/functions
make -C $src/src/tools install-unittests

$bin/$TestName
exit $?
