# testing-ns-0004: Config file to test the backup with postgresql pods

apiVersion: v1
kind: Namespace
metadata:
  name: testing-ns-0004-1
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-client
parameters:
  archiveOnDelete: "false"
provisioner: k8s-sigs.io/nfs-subdir-external-provisioner
reclaimPolicy: Delete
volumeBindingMode: Immediate
---
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"allowVolumeExpansion":true,"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{},"name":"rook-ceph-block"},"parameters":{"clusterID":"rook-ceph","csi.storage.k8s.io/controller-expand-secret-name":"rook-csi-rbd-provisioner","csi.storage.k8s.io/controller-expand-secret-namespace":"rook-ceph","csi.storage.k8s.io/fstype":"ext4","csi.storage.k8s.io/node-stage-secret-name":"rook-csi-rbd-node","csi.storage.k8s.io/node-stage-secret-namespace":"rook-ceph","csi.storage.k8s.io/provisioner-secret-name":"rook-csi-rbd-provisioner","csi.storage.k8s.io/provisioner-secret-namespace":"rook-ceph","imageFeatures":"layering","imageFormat":"2","pool":"replicapool"},"provisioner":"rook-ceph.rbd.csi.ceph.com","reclaimPolicy":"Delete","volumeBindingMode":"Immediate"}
  name: rook-ceph-block
parameters:
  clusterID: rook-ceph
  csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
  csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
  csi.storage.k8s.io/fstype: ext4
  csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
  csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
  csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
  csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
  imageFeatures: layering
  imageFormat: "2"
  pool: replicapool
provisioner: rook-ceph.rbd.csi.ceph.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path
provisioner: rancher.io/local-path
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc-0004-1
  namespace: testing-ns-0004-1
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc-0004-2
  namespace: testing-ns-0004-1
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc-0004-3
  namespace: testing-ns-0004-1
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc-0004-4
  namespace: testing-ns-0004-1
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc-0004-5
  namespace: testing-ns-0004-1
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc-0004-6
  namespace: testing-ns-0004-1
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc-0004-7
  namespace: testing-ns-0004-1
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc-0004-8
  namespace: testing-ns-0004-1
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-0004-1
  namespace: testing-ns-0004-1
spec:
  volumes:
    - name: pvc-0004-1
      persistentVolumeClaim:
        claimName: test-pvc-0004-1
  containers:
    - name: test-container-0004-2
      image: nginx
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/pvc"
          name: pvc-0004-1
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-0004-2
  namespace: testing-ns-0004-1
spec:
  volumes:
    - name: pvc-0004-2
      persistentVolumeClaim:
        claimName: test-pvc-0004-2
  containers:
    - name: test-container-0004-2
      image: nginx
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/pvc"
          name: pvc-0004-2
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-0004-3
  namespace: testing-ns-0004-1
spec:
  volumes:
    - name: pvc-0004-3
      persistentVolumeClaim:
        claimName: test-pvc-0004-3
  containers:
    - name: test-container-0004-3
      image: nginx
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/pvc"
          name: pvc-0004-3
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-0004-4
  namespace: testing-ns-0004-1
spec:
  volumes:
    - name: pvc-0004-4
      persistentVolumeClaim:
        claimName: test-pvc-0004-4
  containers:
    - name: test-container-0004-4
      image: nginx
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/pvc"
          name: pvc-0004-4
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-0004-5
  namespace: testing-ns-0004-1
spec:
  volumes:
    - name: pvc-0004-5
      persistentVolumeClaim:
        claimName: test-pvc-0004-5
  containers:
    - name: test-container-0004-5
      image: nginx
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/pvc"
          name: pvc-0004-5
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-0004-6
  namespace: testing-ns-0004-1
spec:
  volumes:
    - name: pvc-0004-6
      persistentVolumeClaim:
        claimName: test-pvc-0004-6
  containers:
    - name: test-container-0004-6
      image: nginx
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/pvc"
          name: pvc-0004-6
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-0004-7
  namespace: testing-ns-0004-1
spec:
  volumes:
    - name: pvc-0004-7
      persistentVolumeClaim:
        claimName: test-pvc-0004-7
    - name: pvc-0004-8
      persistentVolumeClaim:
        claimName: test-pvc-0004-8
  containers:
    - name: test-container-0004-7
      image: nginx
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/pvc"
          name: pvc-0004-7
        - mountPath: "/pvc2"
          name: pvc-0004-8